apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: clicker-app
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_DB: "events_db"
  POSTGRES_PORT: "5432"
  PORT: "8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: clicker-app
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "SuperSecurePassword123" # Replace with your actual password